//generated by abstract-syntax-gen
package minillvm.ast;
import java.util.*;

public interface GlobalRef extends Element, Const {
    void setGlobal(Global global);
    Global getGlobal();
    Element getParent();
    GlobalRef copy();
    GlobalRef copyWithRefs();
    void clearAttributes();
    void clearAttributesLocal();
    /** */
    public abstract String toString();
    /** */
    public abstract Type calculateType();
}
