//generated by abstract-syntax-gen
package notquitejava.ast;
import java.util.*;

public interface NQJBaseType extends NQJType, NQJElement{
    NQJElement getParent();
    <T> T match(Matcher<T> s);
    void match(MatcherVoid s);
    public interface Matcher<T> {
        T case_TypeInt(NQJTypeInt typeInt);
        T case_TypeBool(NQJTypeBool typeBool);
        T case_TypeClass(NQJTypeClass typeClass);
    }

    public interface MatcherVoid {
        void case_TypeInt(NQJTypeInt typeInt);
        void case_TypeBool(NQJTypeBool typeBool);
        void case_TypeClass(NQJTypeClass typeClass);
    }

    NQJBaseType copy();
    NQJBaseType copyWithRefs();
    /** "information about the source code"*/
    public abstract frontend.SourcePosition getSourcePosition();
    /** "information about the source code"*/
    public abstract void setSourcePosition(frontend.SourcePosition sourcePosition);
    /** null*/
    public abstract analysis.typeinfo.Type getType();
    /** null*/
    public abstract void setType(analysis.typeinfo.Type type);
}
